# Generated by Django 2.0.6 on 2021-08-25 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('pk_id_customer', models.AutoField(primary_key=True, serialize=False)),
                ('name_client', models.CharField(max_length=20)),
                ('surname_client', models.CharField(max_length=20)),
                ('dpi', models.CharField(max_length=12)),
                ('telephone', models.CharField(max_length=8)),
                ('direction', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('pk_num_order', models.AutoField(primary_key=True, serialize=False)),
                ('shipping_address', models.CharField(max_length=80)),
                ('send_date', models.DateField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('fk_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.customer')),
            ],
        ),
        migrations.CreateModel(
            name='seller',
            fields=[
                ('pk_id_seller', models.AutoField(primary_key=True, serialize=False)),
                ('name_seller', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='fk_product',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='fk_product',
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.DeleteModel(
            name='invoice',
        ),
        migrations.DeleteModel(
            name='stock',
        ),
        migrations.AddField(
            model_name='order',
            name='fk_seller',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='storage.seller'),
        ),
    ]
