# Generated by Django 2.0.6 on 2021-08-25 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_auto_20210825_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('pk_num_order', models.AutoField(primary_key=True, serialize=False)),
                ('shipping_address', models.CharField(max_length=80)),
                ('send_date', models.DateField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('fk_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.customer')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
        migrations.AddField(
            model_name='order',
            name='fk_product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='storage.product'),
        ),
    ]
