# Generated by Django 2.0.6 on 2021-09-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_auto_20210825_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen1',
            field=models.URLField(default='https://i.postimg.cc/vBvwPR0x/LOGO.png', max_length=800),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='dpi',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
