# Generated by Django 2.0.6 on 2021-09-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_auto_20210908_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen1',
            field=models.URLField(default='https://i.postimg.cc/VLnwySsn/3aabe0e9a520b9ad90407a82f85adb42.jpg', max_length=800),
        ),
    ]
