# Generated by Django 2.0.6 on 2021-09-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_auto_20210908_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen1',
            field=models.URLField(default='https://i.imgur.com/wNdSAgw.jpg', max_length=800),
        ),
    ]
