# Generated by Django 2.0.6 on 2021-09-23 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0013_auto_20210922_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('pk_contact', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=20)),
                ('mensaje', models.CharField(max_length=150)),
            ],
        ),
    ]
