# Generated by Django 2.0.6 on 2021-09-23 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0015_auto_20210922_2002'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=50),
        ),
    ]
